# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: Home
    url: /
    weight: 10
  - name: Projects
    url: /projects
    weight: 20
  - name: Blog
    url: /blog
    weight: 30
  - name: About
    url: /about
    weight: 40
